version: '3.3'
# https://hub.docker.com/r/linuxserver/openssh-server
# https://hub.docker.com/r/allthings/lsyncd

x-env:
  ssh-server: &ssh-server-env
    - PUID
    - PGID
    - TZ
    - USER_NAME
    - AUTHORIZED_KEYS_FILE=/config/ssh_host_keys/authorized_keys
  lsyncd: &lsyncd-env
    TARGET_USER: ${USER_NAME}
    TARGET_HOST: lsync-target
    TARGET_SSH_PORT: 2222
    TARGET_PATH: /data
    SSH_KEY_FILE: /run/secret/client_key
    HOST_KEY:
    INOTIFY_MODE:
    SYNC_DELAY:
services:
  lsync-a:
    image: solargis/lsyncd
    container_name: lsync-a
    hostname: lsync-a
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.lsyncd
    volumes:
      - ./source-a:/var/source:ro
      - ./keys/client_id_rsa:/run/secret/client_key:ro
    environment: *lsyncd-env
  lsync-b:
    image: solargis/lsyncd
    container_name: lsync-b
    hostname: lsync-b
    restart: unless-stopped
    volumes:
      - ./source-b:/var/source:ro
      - ./keys/client_id_rsa:/run/secret/client_key:ro
    environment: *lsyncd-env

  lsync-target:
    image: solargis/openssh-server
    container_name: lsync-target
    hostname: lsync-target
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.openssh-server
    volumes:
      - ./target:/data
      - ./keys:/config/ssh_host_keys:ro
      #- ./keys/authorized_keys:/config/.ssh/authorized_keys:ro #(works depending on permission mapping)
      #- ./image-openssh-server/usr/bin/ssh-entrypoint.sh:/usr/bin/ssh-entrypoint.sh:ro #(for debuging)
      #- ./image-openssh-server/config/custom-cont-init.d/merge-audthorized_keys:/config/custom-cont-init.d/merge-audthorized_keys:ro #(for debuging)
    environment: *ssh-server-env
    ports:
      - 222:2222

  lsync-backup:
    image: solargis/lsyncd
    container_name: lsync-backup
    hostname: lsync-backup
    restart: unless-stopped
    volumes:
      - ./target:/var/source:ro
      - ./keys/client_id_rsa:/run/secret/client_key:ro
    environment:
      <<: *lsyncd-env
      TARGET_HOST: lsync-replica
      DELETE: 'true'


  lsync-replica:
    image: solargis/openssh-server
    container_name: lsync-replica
    hostname: lsync-replica
    restart: unless-stopped
    volumes:
      - ./target-replica:/data
      - ./keys:/config/ssh_host_keys:ro
    environment: *ssh-server-env